# MySQL 8.0
FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=rigways_acm
ENV MYSQL_USER=rigways_user
ENV MYSQL_PASSWORD=rigways_password

COPY ./sql/ /docker-entrypoint-initdb.d/

EXPOSE 3306

VOLUME ["/var/lib/mysql"]
